name: Generate Snake Animation

# ‡∂ö‡∑Ä‡∂Ø‡∑è‡∂Ø ‡∂∏‡∑ö‡∂ö run ‡∑Ä‡∑ô‡∂±‡∑ä‡∂±‡∑ö
on:
  # UTC time zone ‡∂ë‡∂ö‡∑ö ‡∑Ñ‡∑ê‡∂∏ ‡∂Ø‡∑Ä‡∑É‡∂ö‡∂∏ ‡∂ª‡∑ë 12‡∂ß (‡∂Ω‡∂Ç‡∂ö‡∑è‡∑Ä‡∑ö ‡∂ã‡∂Ø‡∑ö 5.30‡∂ß)
  schedule:
    - cron: "30 0 * * *"
    
  # Actions tab ‡∂ë‡∂ö‡∑ô‡∂±‡∑ä manually run ‡∂ö‡∂ª‡∂±‡∑ä‡∂± ‡∂¥‡∑î‡∑Ö‡∑î‡∑Ä‡∂±‡∑ä
  workflow_dispatch:
  
  # README file ‡∂ë‡∂ö update ‡∂ö‡∂ª‡∑è‡∂∏
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Repository ‡∂ë‡∂ö checkout ‡∂ö‡∂ª‡∂ú‡∂±‡∑ä‡∂±‡∑Ä‡∑è
      - name: Checkout
        uses: actions/checkout@v3
      
      # Snake SVG files generate ‡∂ö‡∂ª‡∂±‡∑Ä‡∑è
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Generated files push ‡∂ö‡∂ª‡∂±‡∑Ä‡∑è
      - name: Push Snake files
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: 'üêç Update snake animation'
